
# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  nodejs_version: "Stable"


build: off

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - ps: $env:path = $env:appdata + "\npm;" + $env:path
  - npm install && npm install karma-ie-launcher

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues

  - ps: "npm --version # PowerShell" # Pass comment to PS for easier debugging
  - npm run tests.all

notifications:
  - provider: Webhook
    url: https://
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

cache: node_modules
